export const researchHubCopy = {
  en: {
    designs: 'Study designs',
    multiKicker: 'Multi-round · two groups · method revisions',
    multiTitle: 'Multi-round coevolution',
    multiBody: 'Participants alternate independent judgment, Agent help and independent transfer across rounds. Reviewed method revisions take effect in the next round for one group only, so you can compare updating against a frozen method.',
    multiOpen: 'Open multi-round studies',
    multiStats: (count: number, active: number, pending: number) => count ? `${count} frozen · ${active} in progress · ${pending} awaiting review` : 'No study frozen yet',
    fourKicker: 'Single session · four stages · conditions',
    fourTitle: 'Four-stage study',
    fourBody: 'One initial judgment, one practice with help under an assigned condition, a new situation and a delayed situation. Supports participant invitations, isolated Agent help and independent reviewer packets.',
    fourStats: (count: number) => count ? `${count} draft${count === 1 ? '' : 's'} below` : 'No draft yet; start below',
    fourOpen: 'Drafts below',
    loading: 'Loading…',
    readiness: 'Before a pilot',
    modelReady: (summary: string) => `Fixed model ready: ${summary}`,
    modelMissing: 'Configure a compatible model in AI settings. New protocols freeze the current model, temperature and reply budget.',
    aiSettings: 'AI settings',
    accessReady: 'Access protection is on: Web password and access token are configured.',
    accessMissing: 'Enable a Web password and an access token before creating participant links. Remote participation requires HTTPS.',
    settings: 'Open Settings',
    materials: 'Review tasks, scoring references and consent text yourself. Example materials are not calibrated, and completing a pilot does not show a learning effect.',
    unknown: 'Could not read readiness right now. Retry before inviting anyone.',
    retry: 'Retry',
    checklist: 'Pilot checklist',
    steps: [
      'Walk through a study yourself first, titled as a workflow trial that stays out of analysis.',
      'Set at least 24 hours between rounds for real cross-day returns; 0 is for workflow checks only.',
      'Review task difficulty, acceptable answers and scoring references before freezing.',
      'Send each private link to one consenting person only; never publish links.',
      'Review revisions on evidence and stated scope, not on which group a participant is in.',
      'Keep failed model replies as failures; retry explicitly after fixing configuration.',
      'Score from the blind review packet; open the packet key only after scoring.',
    ],
  },
  zh: {
    designs: '研究设计',
    multiKicker: '多轮 · 两组 · 方法修订',
    multiTitle: '多轮共同进化',
    multiBody: '参与者每轮依次完成独立判断、借助 Agent 帮助和独立迁移。审核通过的方法修订只在一组的下一轮生效，可对照“更新生效”与“全程初始方法”。',
    multiOpen: '打开多轮研究',
    multiStats: (count: number, active: number, pending: number) => count ? `${count} 项已冻结 · ${active} 位进行中 · ${pending} 份待审核` : '尚未冻结研究',
    fourKicker: '单次 · 四阶段 · 比较条件',
    fourTitle: '四阶段研究',
    fourBody: '一次初始判断、一次按分配条件获得帮助的练习、一个新情境和一个延迟情境。支持参与者邀请、隔离的 Agent 帮助和独立评审工作包。',
    fourStats: (count: number) => count ? `下方有 ${count} 份草稿` : '还没有草稿，从下方开始',
    fourOpen: '草稿在下方',
    loading: '正在读取…',
    readiness: '试跑之前',
    modelReady: (summary: string) => `固定模型已就绪：${summary}`,
    modelMissing: '请先在 AI 设置中配置兼容模型。新协议会冻结当前模型、温度和回复预算。',
    aiSettings: 'AI 设置',
    accessReady: '访问保护已开启：已配置网页密码和访问令牌。',
    accessMissing: '创建参与链接前，请启用网页密码和访问令牌；远程参与需使用 HTTPS。',
    settings: '打开设置',
    materials: '题目、评分参考与知情说明需由负责人自行审核。示例材料未经校准，完成试跑也不代表学习效果。',
    unknown: '暂时无法读取就绪状态，邀请前请重试。',
    retry: '重试',
    checklist: '试跑清单',
    steps: [
      '负责人先自己走一遍，标题注明流程试用、不纳入分析。',
      '真实跨天返回至少间隔 24 小时；0 小时只用于流程检查。',
      '冻结前审核题目难度、可接受答案和评分参考。',
      '每份私有链接只发给一位已同意的参与者，不公开发布。',
      '依据证据和范围声明审核修订，不因组别改变标准。',
      '模型失败保留为失败；修复配置后再显式重试。',
      '用盲评工作包评分，评分完成后再打开工作包密钥。',
    ],
  },
};
